#!/bin/bash

# functiond declaration
getDate(){
	date

	return
}

# function call
# don't need brackets when calling functions

getDate

#	global vs local


# global
name="Yuxuan"

demLocal(){
	local name="wayne"
	return
}

demLocal

echo "$name"

# name inside function will always be local, (wayne), and outside the function it will be the global version (Yuxuan)


getSum(){
	local num3=$1
	local num4=$2

	local sum=$((num3+num4))
	# this echo is returning the value
	echo $sum
}

num1=5
num2=6

# don't need () or commas when passing in values to functions
sum=$(getSum num1 num2)
echo "The sum is $sum"






